server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exit_flow?createDatabaseIfNotExist=true
    username: root
    password: 17082002Pm!
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
