
server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exit_flow?createDatabaseIfNotExist=true
    username: root
    password: 17082002Pm!
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    username: baibhavmishra3211@gmail.com
    password: lainyznzwwndijjd
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
jwt:
  secret:
    key: secretKey

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
