
server:
  port: 9000

# docker network inspect <network_name> => gives info of containers running in the network
# In data source url, 172.18.0.4:3306 is the ip address of the localmysql in docker container
spring:
  datasource:
    url: jdbc:mysql://172.18.0.4:3306/exit_flow?createDatabaseIfNotExist=true
    username: root
    password: R@ju.kr50
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    username: baibhavmishra3211@gmail.com
    password: lainyznzwwndijjd
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
jwt:
  secret:
    key: secretKey

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
